import { useState, useEffect, useMemo } from 'react'
import { X, Loader2, AlertCircle, Save, Plus, Hash, Type, Calendar, Clock, ToggleLeft, Braces, Table2, Sparkles, Ban } from 'lucide-react'
import { postgresqlService } from '@/services/postgresql.service'

interface ColumnSchema {
  column_name: string
  data_type: string
  is_nullable: string
  column_default: string | null
  character_maximum_length: number | null
  numeric_precision: number | null
  numeric_scale: number | null
}

interface SQLRowEditorModalProps {
  mode: 'insert' | 'edit'
  doc: Record<string, any>
  connectionId: string
  database: string
  table: string
  onSave: (data: Record<string, any>) => void
  onClose: () => void
}

function getInputType(dataType: string): string {
  const t = dataType.toLowerCase()
  if (['integer', 'bigint', 'smallint', 'numeric', 'decimal', 'real', 'double precision', 'serial', 'bigserial'].some(n => t.includes(n))) return 'number'
  if (t.includes('boolean')) return 'checkbox'
  if (t === 'date') return 'date'
  if (t.includes('timestamp')) return 'datetime-local'
  if (t.includes('time') && !t.includes('timestamp')) return 'time'
  return 'text'
}

function isAutoGenerated(col: ColumnSchema): boolean {
  const def = col.column_default || ''
  return def.includes('nextval(') || def.includes('gen_random_uuid')
}

function isJsonType(dataType: string): boolean {
  const t = dataType.toLowerCase()
  return t === 'json' || t === 'jsonb'
}

function isTextLong(col: ColumnSchema): boolean {
  const t = col.data_type.toLowerCase()
  return t === 'text' || (t.includes('character') && (col.character_maximum_length === null || col.character_maximum_length > 255))
}

/** Convert a date value from DB into the format required by HTML date/time inputs */
function formatDateForInput(value: any, inputType: string): string {
  if (value === null || value === undefined || value === '') return ''
  const str = String(value)

  try {
    const d = new Date(str)
    if (isNaN(d.getTime())) return str

    if (inputType === 'date') {
      return d.toISOString().slice(0, 10)
    }
    if (inputType === 'datetime-local') {
      const pad = (n: number) => String(n).padStart(2, '0')
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
    }
    if (inputType === 'time') {
      const pad = (n: number) => String(n).padStart(2, '0')
      return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
    }
  } catch {
    // fallback
  }
  return str
}

function getTypeIcon(dataType: string) {
  const t = dataType.toLowerCase()
  if (['integer', 'bigint', 'smallint', 'numeric', 'decimal', 'real', 'double precision', 'serial', 'bigserial'].some(n => t.includes(n))) return Hash
  if (t.includes('boolean')) return ToggleLeft
  if (t === 'date') return Calendar
  if (t.includes('timestamp')) return Calendar
  if (t.includes('time')) return Clock
  if (t === 'json' || t === 'jsonb') return Braces
  return Type
}

function getTypeBadgeColor(dataType: string): string {
  const t = dataType.toLowerCase()
  if (['integer', 'bigint', 'smallint', 'serial', 'bigserial'].some(n => t.includes(n))) return 'text-blue-400 bg-blue-500/10 border-blue-500/20'
  if (['numeric', 'decimal', 'real', 'double'].some(n => t.includes(n))) return 'text-cyan-400 bg-cyan-500/10 border-cyan-500/20'
  if (t.includes('boolean')) return 'text-amber-400 bg-amber-500/10 border-amber-500/20'
  if (t.includes('timestamp') || t === 'date' || t.includes('time')) return 'text-purple-400 bg-purple-500/10 border-purple-500/20'
  if (t === 'json' || t === 'jsonb') return 'text-orange-400 bg-orange-500/10 border-orange-500/20'
  if (t === 'uuid') return 'text-pink-400 bg-pink-500/10 border-pink-500/20'
  return 'text-muted-foreground bg-muted/50 border-border'
}

export function SQLRowEditorModal({ mode, doc, connectionId, database, table, onSave, onClose }: SQLRowEditorModalProps) {
  const [columns, setColumns] = useState<ColumnSchema[]>([])
  const [formData, setFormData] = useState<Record<string, any>>({})
  const [nullFields, setNullFields] = useState<Set<string>>(new Set())
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    loadSchema()
  }, [connectionId, database, table])

  const loadSchema = async () => {
    try {
      setLoading(true)
      const result = await postgresqlService.getTableSchema(connectionId, database, table)
      if (result.success && result.columns) {
        setColumns(result.columns)
        const initial: Record<string, any> = {}
        const initialNulls = new Set<string>()
        result.columns.forEach((col: ColumnSchema) => {
          if (mode === 'edit' && doc[col.column_name] !== undefined) {
            if (doc[col.column_name] === null) {
              initialNulls.add(col.column_name)
              initial[col.column_name] = ''
            } else {
              const inputType = getInputType(col.data_type)
              if (inputType === 'date' || inputType === 'datetime-local' || inputType === 'time') {
                initial[col.column_name] = formatDateForInput(doc[col.column_name], inputType)
              } else {
                initial[col.column_name] = doc[col.column_name]
              }
            }
          } else if (mode === 'insert' && isAutoGenerated(col)) {
            initial[col.column_name] = undefined
          } else {
            const inputType = getInputType(col.data_type)
            initial[col.column_name] = inputType === 'checkbox' ? false : ''
          }
        })
        setFormData(initial)
        setNullFields(initialNulls)
      } else {
        setError(result.error || 'Failed to load table schema')
      }
    } catch (e: any) {
      setError(e.message || 'Failed to load schema')
    } finally {
      setLoading(false)
    }
  }

  const handleChange = (colName: string, value: any) => {
    setFormData(prev => ({ ...prev, [colName]: value }))
    // If user starts typing, remove from null set
    if (nullFields.has(colName)) {
      setNullFields(prev => { const n = new Set(prev); n.delete(colName); return n })
    }
  }

  const toggleNull = (colName: string) => {
    setNullFields(prev => {
      const n = new Set(prev)
      if (n.has(colName)) {
        n.delete(colName)
      } else {
        n.add(colName)
      }
      return n
    })
  }

  const handleSubmit = () => {
    setSaving(true)
    try {
      const data: Record<string, any> = {}
      columns.forEach(col => {
        // Handle explicit NULL
        if (nullFields.has(col.column_name)) {
          data[col.column_name] = null
          return
        }
        const val = formData[col.column_name]
        if (mode === 'insert' && isAutoGenerated(col) && (val === undefined || val === '')) return
        if (val === '' || val === undefined) {
          if (col.is_nullable === 'YES' || col.column_default !== null) return
        }
        const inputType = getInputType(col.data_type)
        if (inputType === 'number' && val !== '' && val !== undefined) {
          data[col.column_name] = Number(val)
        } else if (inputType === 'checkbox') {
          data[col.column_name] = Boolean(val)
        } else if (isJsonType(col.data_type) && typeof val === 'string' && val.trim()) {
          try { data[col.column_name] = JSON.parse(val) } catch { data[col.column_name] = val }
        } else if (val !== undefined && val !== '') {
          data[col.column_name] = val
        }
      })
      onSave(data)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setSaving(false)
    }
  }

  const isRequired = (col: ColumnSchema) => col.is_nullable === 'NO' && !col.column_default && !isAutoGenerated(col)

  // Group columns: auto-generated first (collapsed in insert), then regular
  const { autoColumns, regularColumns } = useMemo(() => {
    const auto: ColumnSchema[] = []
    const regular: ColumnSchema[] = []
    columns.forEach(col => {
      if (isAutoGenerated(col)) auto.push(col)
      else regular.push(col)
    })
    return { autoColumns: auto, regularColumns: regular }
  }, [columns])

  const filledCount = useMemo(() => {
    return columns.filter(col => {
      const val = formData[col.column_name]
      return val !== undefined && val !== '' && !isAutoGenerated(col)
    }).length
  }, [formData, columns])

  const renderField = (col: ColumnSchema) => {
    const inputType = getInputType(col.data_type)
    const autoGen = isAutoGenerated(col)
    const required = isRequired(col)
    const val = formData[col.column_name]
    const isNull = nullFields.has(col.column_name)
    const nullable = col.is_nullable === 'YES'
    const TypeIcon = getTypeIcon(col.data_type)
    const badgeColor = getTypeBadgeColor(col.data_type)
    const isDisabled = (autoGen && mode === 'insert') || isNull

    return (
      <div key={col.column_name} className={`group rounded-lg border p-3 transition-all duration-150 ${
        isNull ? 'bg-muted/30 border-border/50' :
        autoGen && mode === 'insert' ? 'bg-muted/20 border-border/30 opacity-60' :
        'bg-card hover:border-primary/20 hover:shadow-sm'
      }`}>
        {/* Field header */}
        <div className="flex items-center gap-2 mb-2">
          <TypeIcon className={`h-3.5 w-3.5 shrink-0 ${isNull ? 'text-muted-foreground/40' : 'text-muted-foreground'}`} />
          <span className={`text-[12px] font-semibold truncate ${isNull ? 'text-muted-foreground/50 line-through' : ''}`}>
            {col.column_name}
          </span>
          {required && <span className="text-destructive text-[10px] font-bold">*</span>}
          {autoGen && (
            <span className="flex items-center gap-0.5 text-[9px] font-medium text-muted-foreground px-1.5 py-0.5 rounded bg-muted/50 border border-border/50">
              <Sparkles className="h-2.5 w-2.5" /> AUTO
            </span>
          )}
          <div className="flex-1" />
          <span className={`text-[9px] font-mono font-medium px-1.5 py-0.5 rounded-md border ${badgeColor}`}>
            {col.data_type.toUpperCase()}
            {col.character_maximum_length ? `(${col.character_maximum_length})` : ''}
          </span>
          {nullable && !autoGen && (
            <button
              type="button"
              onClick={() => toggleNull(col.column_name)}
              title={isNull ? 'Remove NULL' : 'Set to NULL'}
              className={`flex items-center gap-0.5 text-[9px] font-medium px-1.5 py-0.5 rounded-md border transition-all duration-150 ${
                isNull
                  ? 'bg-amber-500/15 text-amber-400 border-amber-500/30'
                  : 'text-muted-foreground/50 border-border/50 hover:text-muted-foreground hover:border-border'
              }`}
            >
              <Ban className="h-2.5 w-2.5" />
              NULL
            </button>
          )}
        </div>

        {/* Field input */}
        {isNull ? (
          <div className="h-8 flex items-center px-3 rounded-md bg-muted/30 border border-dashed border-border/50">
            <span className="text-[11px] text-muted-foreground/50 italic">NULL</span>
          </div>
        ) : inputType === 'checkbox' ? (
          <label className="flex items-center gap-2.5 h-8 px-3 rounded-md bg-muted/30 border border-border/50 cursor-pointer hover:bg-muted/50 transition-colors">
            <div className={`relative h-5 w-9 rounded-full transition-colors duration-200 ${val ? 'bg-primary' : 'bg-muted-foreground/20'}`}>
              <div className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${val ? 'translate-x-4' : 'translate-x-0.5'}`} />
            </div>
            <input type="checkbox" checked={!!val}
              onChange={e => handleChange(col.column_name, e.target.checked)}
              className="sr-only"
              disabled={isDisabled} />
            <span className={`text-[11px] font-mono font-medium ${val ? 'text-primary' : 'text-muted-foreground'}`}>
              {val ? 'true' : 'false'}
            </span>
          </label>
        ) : isJsonType(col.data_type) ? (
          <textarea
            className="w-full h-24 rounded-md border bg-background px-3 py-2 text-[11px] font-mono focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary/50 resize-none transition-shadow placeholder:text-muted-foreground/30"
            value={typeof val === 'object' ? JSON.stringify(val, null, 2) : (val ?? '')}
            onChange={e => handleChange(col.column_name, e.target.value)}
            placeholder={autoGen && mode === 'insert' ? '(auto-generated)' : '{ }'}
            disabled={isDisabled}
            spellCheck={false}
          />
        ) : isTextLong(col) ? (
          <textarea
            className="w-full h-16 rounded-md border bg-background px-3 py-2 text-[11px] focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary/50 resize-none transition-shadow placeholder:text-muted-foreground/30"
            value={val ?? ''}
            onChange={e => handleChange(col.column_name, e.target.value)}
            placeholder={autoGen && mode === 'insert' ? '(auto-generated)' : col.column_default ? `Default: ${col.column_default}` : ''}
            disabled={isDisabled}
          />
        ) : (
          <input
            className="w-full h-8 rounded-md border bg-background px-3 text-[11px] focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary/50 transition-shadow placeholder:text-muted-foreground/30 disabled:bg-muted/30 disabled:text-muted-foreground/50"
            type={inputType}
            value={val ?? ''}
            onChange={e => handleChange(col.column_name, e.target.value)}
            placeholder={autoGen && mode === 'insert' ? '(auto-generated)' : col.column_default ? `Default: ${col.column_default}` : ''}
            disabled={isDisabled}
            step={inputType === 'number' && (col.data_type.toLowerCase().includes('numeric') || col.data_type.toLowerCase().includes('decimal') || col.data_type.toLowerCase().includes('real') || col.data_type.toLowerCase().includes('double')) ? 'any' : undefined}
          />
        )}
      </div>
    )
  }

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 animate-fade-in" onClick={onClose}>
      <div className="bg-background border rounded-xl w-[640px] max-h-[85vh] flex flex-col shadow-2xl animate-scale-in" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b bg-card/50 rounded-t-xl">
          <div className="flex items-center gap-3">
            <div className={`p-1.5 rounded-lg ${mode === 'edit' ? 'bg-primary/10' : 'bg-success/10'}`}>
              {mode === 'edit' ? <Save className="h-4 w-4 text-primary" /> : <Plus className="h-4 w-4 text-success" />}
            </div>
            <div>
              <h3 className="text-sm font-semibold">{mode === 'edit' ? 'Edit Row' : 'Insert Row'}</h3>
              <div className="flex items-center gap-1.5 mt-0.5">
                <Table2 className="h-3 w-3 text-muted-foreground" />
                <span className="text-[10px] text-muted-foreground font-mono">{table}</span>
                {!loading && (
                  <span className="text-[10px] text-muted-foreground/50 ml-1">
                    {filledCount}/{regularColumns.length} fields
                  </span>
                )}
              </div>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-accent transition-colors">
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-4">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-12 gap-3">
              <div className="p-3 rounded-full bg-muted/50">
                <Loader2 className="h-5 w-5 animate-spin text-primary" />
              </div>
              <span className="text-xs text-muted-foreground">Loading table schema...</span>
            </div>
          ) : error ? (
            <div className="flex items-center gap-2.5 p-3.5 rounded-xl bg-destructive/10 border border-destructive/20">
              <AlertCircle className="h-4 w-4 text-destructive shrink-0" />
              <span className="text-xs text-destructive">{error}</span>
            </div>
          ) : (
            <div className="space-y-2">
              {/* Auto-generated fields (collapsed for insert) */}
              {autoColumns.length > 0 && mode === 'insert' && (
                <div className="mb-3">
                  <div className="flex items-center gap-2 mb-2">
                    <Sparkles className="h-3 w-3 text-muted-foreground/50" />
                    <span className="text-[10px] font-medium text-muted-foreground/60 uppercase tracking-wider">Auto-generated</span>
                    <div className="flex-1 h-px bg-border/30" />
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    {autoColumns.map(renderField)}
                  </div>
                </div>
              )}
              {autoColumns.length > 0 && mode === 'edit' && (
                <div className="mb-3">
                  <div className="flex items-center gap-2 mb-2">
                    <Sparkles className="h-3 w-3 text-muted-foreground/50" />
                    <span className="text-[10px] font-medium text-muted-foreground/60 uppercase tracking-wider">Auto-generated</span>
                    <div className="flex-1 h-px bg-border/30" />
                  </div>
                  <div className="space-y-2">
                    {autoColumns.map(renderField)}
                  </div>
                </div>
              )}

              {/* Regular fields */}
              {regularColumns.length > 0 && autoColumns.length > 0 && (
                <div className="flex items-center gap-2 mb-2">
                  <Type className="h-3 w-3 text-muted-foreground/50" />
                  <span className="text-[10px] font-medium text-muted-foreground/60 uppercase tracking-wider">Fields</span>
                  <div className="flex-1 h-px bg-border/30" />
                </div>
              )}
              <div className="space-y-2">
                {regularColumns.map(renderField)}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-5 py-3 border-t bg-card/30 rounded-b-xl">
          <div className="text-[10px] text-muted-foreground">
            {columns.length > 0 && !loading && (
              <>
                {columns.length} columns
                {nullFields.size > 0 && <span className="text-amber-400 ml-2">{nullFields.size} set to NULL</span>}
              </>
            )}
          </div>
          <div className="flex gap-2">
            <button onClick={onClose} className="h-8 px-4 rounded-lg border text-[11px] font-medium hover:bg-accent transition-all duration-150 active:scale-[0.97]">
              Cancel
            </button>
            <button onClick={handleSubmit} disabled={loading || saving}
              className={`h-8 px-5 rounded-lg text-[11px] font-medium shadow-sm transition-all duration-150 active:scale-[0.97] disabled:opacity-50 ${
                mode === 'edit'
                  ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                  : 'bg-emerald-600 text-white hover:bg-emerald-700'
              }`}>
              {saving ? (
                <span className="flex items-center gap-1.5">
                  <Loader2 className="h-3 w-3 animate-spin" />
                  Saving...
                </span>
              ) : mode === 'edit' ? (
                <span className="flex items-center gap-1.5">
                  <Save className="h-3 w-3" />
                  Update Row
                </span>
              ) : (
                <span className="flex items-center gap-1.5">
                  <Plus className="h-3 w-3" />
                  Insert Row
                </span>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
