import { useState, useEffect } from 'react'
import { X, Loader2, AlertCircle } from 'lucide-react'
import { postgresqlService } from '@/services/postgresql.service'

interface ColumnSchema {
  column_name: string
  data_type: string
  is_nullable: string
  column_default: string | null
  character_maximum_length: number | null
  numeric_precision: number | null
  numeric_scale: number | null
}

interface SQLRowEditorModalProps {
  mode: 'insert' | 'edit'
  doc: Record<string, any>
  connectionId: string
  database: string
  table: string
  onSave: (data: Record<string, any>) => void
  onClose: () => void
}

function getInputType(dataType: string): string {
  const t = dataType.toLowerCase()
  if (['integer', 'bigint', 'smallint', 'numeric', 'decimal', 'real', 'double precision', 'serial', 'bigserial'].some(n => t.includes(n))) return 'number'
  if (t.includes('boolean')) return 'checkbox'
  if (t === 'date') return 'date'
  if (t.includes('timestamp')) return 'datetime-local'
  if (t.includes('time') && !t.includes('timestamp')) return 'time'
  return 'text'
}

function isAutoGenerated(col: ColumnSchema): boolean {
  const def = col.column_default || ''
  return def.includes('nextval(') || def.includes('gen_random_uuid')
}

function isJsonType(dataType: string): boolean {
  const t = dataType.toLowerCase()
  return t === 'json' || t === 'jsonb'
}

const IC = 'w-full h-8 rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring'

export function SQLRowEditorModal({ mode, doc, connectionId, database, table, onSave, onClose }: SQLRowEditorModalProps) {
  const [columns, setColumns] = useState<ColumnSchema[]>([])
  const [formData, setFormData] = useState<Record<string, any>>({})
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    loadSchema()
  }, [connectionId, database, table])

  const loadSchema = async () => {
    try {
      setLoading(true)
      const result = await postgresqlService.getTableSchema(connectionId, database, table)
      if (result.success && result.columns) {
        setColumns(result.columns)
        // Initialize form data
        const initial: Record<string, any> = {}
        result.columns.forEach((col: ColumnSchema) => {
          if (mode === 'edit' && doc[col.column_name] !== undefined) {
            initial[col.column_name] = doc[col.column_name]
          } else if (mode === 'insert' && isAutoGenerated(col)) {
            initial[col.column_name] = undefined // skip auto-generated
          } else {
            const inputType = getInputType(col.data_type)
            initial[col.column_name] = inputType === 'checkbox' ? false : ''
          }
        })
        setFormData(initial)
      } else {
        setError(result.error || 'Failed to load table schema')
      }
    } catch (e: any) {
      setError(e.message || 'Failed to load schema')
    } finally {
      setLoading(false)
    }
  }

  const handleChange = (colName: string, value: any) => {
    setFormData(prev => ({ ...prev, [colName]: value }))
  }

  const handleSubmit = () => {
    setSaving(true)
    try {
      const data: Record<string, any> = {}
      columns.forEach(col => {
        const val = formData[col.column_name]
        // Skip auto-generated fields on insert if empty
        if (mode === 'insert' && isAutoGenerated(col) && (val === undefined || val === '')) return
        // Skip empty optional fields
        if (val === '' || val === undefined) {
          if (col.is_nullable === 'YES' || col.column_default !== null) return
        }
        // Convert types
        const inputType = getInputType(col.data_type)
        if (inputType === 'number' && val !== '' && val !== undefined) {
          data[col.column_name] = Number(val)
        } else if (inputType === 'checkbox') {
          data[col.column_name] = Boolean(val)
        } else if (isJsonType(col.data_type) && typeof val === 'string' && val.trim()) {
          try { data[col.column_name] = JSON.parse(val) } catch { data[col.column_name] = val }
        } else if (val !== undefined && val !== '') {
          data[col.column_name] = val
        }
      })
      onSave(data)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setSaving(false)
    }
  }

  const isRequired = (col: ColumnSchema) => col.is_nullable === 'NO' && !col.column_default && !isAutoGenerated(col)

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60" onClick={onClose}>
      <div className="bg-background border border-border rounded-lg w-[600px] max-h-[80vh] flex flex-col shadow-2xl" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border">
          <h3 className="text-sm font-semibold">{mode === 'edit' ? 'Edit Row' : 'Insert Row'} — {table}</h3>
          <button onClick={onClose} className="p-1 rounded hover:bg-accent"><X className="h-4 w-4" /></button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {loading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              <span className="ml-2 text-xs text-muted-foreground">Loading schema...</span>
            </div>
          ) : error ? (
            <div className="flex items-center gap-2 p-3 rounded-md bg-destructive/10 border border-destructive/20">
              <AlertCircle className="h-4 w-4 text-destructive" />
              <span className="text-xs text-destructive">{error}</span>
            </div>
          ) : (
            columns.map(col => {
              const inputType = getInputType(col.data_type)
              const autoGen = isAutoGenerated(col)
              const required = isRequired(col)
              const val = formData[col.column_name]

              return (
                <div key={col.column_name} className={`space-y-1 ${autoGen && mode === 'insert' ? 'opacity-50' : ''}`}>
                  <div className="flex items-center gap-1.5">
                    <label className="text-xs font-medium">{col.column_name}</label>
                    {required && <span className="text-destructive text-xs">*</span>}
                    <span className="text-[10px] text-muted-foreground ml-auto">
                      {col.data_type.toUpperCase()}
                      {col.character_maximum_length ? `(${col.character_maximum_length})` : ''}
                      {col.is_nullable === 'NO' ? ' · NOT NULL' : ''}
                      {autoGen ? ' · AUTO' : ''}
                    </span>
                  </div>
                  {inputType === 'checkbox' ? (
                    <label className="flex items-center gap-2 text-xs">
                      <input type="checkbox" checked={!!val}
                        onChange={e => handleChange(col.column_name, e.target.checked)}
                        className="rounded border-input"
                        disabled={autoGen && mode === 'insert'} />
                      {val ? 'true' : 'false'}
                    </label>
                  ) : isJsonType(col.data_type) ? (
                    <textarea
                      className="w-full h-20 rounded-md border border-input bg-background px-3 py-2 text-xs font-mono focus:outline-none focus:ring-2 focus:ring-ring resize-none"
                      value={typeof val === 'object' ? JSON.stringify(val, null, 2) : (val ?? '')}
                      onChange={e => handleChange(col.column_name, e.target.value)}
                      placeholder={autoGen && mode === 'insert' ? '(auto-generated)' : '{}'}
                      disabled={autoGen && mode === 'insert'}
                    />
                  ) : (
                    <input
                      className={IC}
                      type={inputType}
                      value={val ?? ''}
                      onChange={e => handleChange(col.column_name, e.target.value)}
                      placeholder={autoGen && mode === 'insert' ? '(auto-generated)' : col.column_default ? `Default: ${col.column_default}` : ''}
                      disabled={autoGen && mode === 'insert'}
                      step={inputType === 'number' && (col.data_type.toLowerCase().includes('numeric') || col.data_type.toLowerCase().includes('decimal') || col.data_type.toLowerCase().includes('real') || col.data_type.toLowerCase().includes('double')) ? 'any' : undefined}
                    />
                  )}
                </div>
              )
            })
          )}
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-2 px-4 py-3 border-t border-border">
          <button onClick={onClose} className="h-8 px-4 rounded-md border border-input bg-background text-sm font-medium hover:bg-accent">Cancel</button>
          <button onClick={handleSubmit} disabled={loading || saving}
            className="h-8 px-4 rounded-md bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 disabled:opacity-50">
            {saving ? 'Saving...' : mode === 'edit' ? 'Update' : 'Insert'}
          </button>
        </div>
      </div>
    </div>
  )
}

